title: Dovs' Personal Blog
name: "Hugo's Personal Blog"
author: Hugo Siqueira Gomes
email: hugodovs@gmail.com
twitter_username: hugodovs
github_username:  hugodovs
description: >-
  Repository of hugodovs' brain.
baseurl: "" 
profile_url: "http://memoriesofzattera.github.io"


#Paginate in Blog:
paginate: 3
paginate_path: "/blog/page:num"

# Build settings
theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
collections:
  projects: 
    output: true
    #layout: project
    #image: https://via.placeholder.com/800x600
    #show_sidebar: false